[package]
name = "smpt"
version = "0.1.5"
edition = "2021"

[dependencies]
home = "0.5"
git2 = { version = "0.19", default_features = false }
clap = { version = "4.5", features = ["derive"] }

[profile.release]
lto = true
opt-level = 3
panic = "abort"
codegen-units = 1
